version: 2
updates:
  # Maintain dependencies for gomod
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
    commit-message:
      prefix: "gomod"
    open-pull-requests-limit: 1
    pull-request-branch-name:
      separator: "_"
    reviewers:
      - "bogdanserdinov"
