// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package kaminarigosdk is a generated GoMock package.
package kaminarigosdk

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// CreateLightningInvoice mocks base method.
func (m *MockInterface) CreateLightningInvoice(arg0 *CreateInvoiceRequest) (*CreateLightningInvoiceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLightningInvoice", arg0)
	ret0, _ := ret[0].(*CreateLightningInvoiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLightningInvoice indicates an expected call of CreateLightningInvoice.
func (mr *MockInterfaceMockRecorder) CreateLightningInvoice(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLightningInvoice", reflect.TypeOf((*MockInterface)(nil).CreateLightningInvoice), arg0)
}

// CreateOnChainInvoice mocks base method.
func (m *MockInterface) CreateOnChainInvoice(arg0 *CreateInvoiceRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOnChainInvoice", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOnChainInvoice indicates an expected call of CreateOnChainInvoice.
func (mr *MockInterfaceMockRecorder) CreateOnChainInvoice(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOnChainInvoice", reflect.TypeOf((*MockInterface)(nil).CreateOnChainInvoice), arg0)
}
